
image:
  tag: test-latest

replicas: 1
containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  paths:
    - path: /api/opsscheduler/(.*)
      serviceName: rats-backend-ws-ops-scheduler-test-service
      servicePort: 80
