image:
  tag: prod-latest

replicas: 2
containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  paths:
    - path: /api/opsscheduler/v3/api-docs
      serviceName: rats-backend-ws-ops-scheduler-prod-service
      servicePort: 80
    - path: /api/opsscheduler/(.*)
      serviceName: rats-backend-ws-ops-scheduler-prod-service
      servicePort: 80
