image:
  tag: prod-latest

replicas: 2
containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  paths:
    - path: /api/opsscheduler/(.*)
      serviceName: rcal-ops-scheduler-prod-service
      servicePort: 80